test:
  adapter: redis
  url: <%= ENV.fetch("TEST_REDIS_URL") { "redis://localhost:6378/1" } %>
  channel_prefix: hermes_test
  pool_size: 5

development:
  adapter: redis
  url: <%= ENV.fetch("DEVELOPMENT_REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: hermes_development
  pool_size: 5

production:
  adapter: redis
  url: <%= ENV.fetch("PRODUCTION_REDIS_URL") { "redis://localhost:6380/1" } %>
  channel_prefix: hermes_production
  pool_size: 5