name: Run Tests on Pull Requests

on:
  pull_request:
    branches:
      - develop  # This will run the tests when a PR is created/updated targeting the `develop` branch
    paths:
      - '**/*.rb'  # You can specify the paths that should trigger the action

jobs:
  test:
    runs-on: ubuntu-latest  # You can choose the OS based on your environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2' # Specify your Ruby version here (adjust as per your project)

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up database (optional for Rails)
        run: |
          bin/rails db:create
          bin/rails db:migrate
          bin/rails db:seed

      - name: Run tests
        run: |
          bundle exec rspec  # Replace with your test command, e.g., rspec, rails test, etc.
